Source/VMware.vSphereDSC/Tests/Integration/vCenterSettings.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/vCenterStatistics.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/IntegrationTests.ps1

should quick-fix issue #6
Signed-off-by: Markus Fischbacher <fischbacher.markus@gmail.com>

Added mandatory parameters

---

README.md

Added clarification to README.md that PowerShell core is not supported.
Signed-off-by: Brett Johnson <brett@sdbrett.com>

Add note that PS core not supported

---

Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSettings/VMHostSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostSettings.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/vCenterSettings.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostSettings.Unit.Tests.ps1

New attempt to get these tests merged.
The files are now formatted with the workspace settings, so the diffs should be better.

VMHostSettings & vCenterSettings Integration tests

---

COMMITTING_GUIDELINES.md

Added COMMITTING_GUIDELINES.md

---

Documentation/DSCResources/VMHostService/VMHostService.md
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostService_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostService.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostService/VMHostService_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostService.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
Source/VMware.vSphereDSC/Tests/Unit/VMHostService.Unit.Tests.ps1

Initial version
Date: Sat 05-01-2019
Time: 00:02
Signed-off-by:  Luc Dekens <dekens.luc@gmail.com>

VMHostService

---

Documentation/DSCResources/VMHostSyslog/VMHostSyslog.md
Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSyslog/VMHostSyslog_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostSyslog.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
Source/VMware.vSphereDSC/Tests/Unit/VMHostSyslog.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

New commit based on new fork from master
Date: Wed 09-01-2019
Time: 07:51
Signed-off-by: Luc Dekens <dekens.luc@gmail.com>

VMHostSyslog

---

Documentation/DSCResources/PowerCLISettings/PowerCLISettings.md
Documentation/DSCResources/VMHostDnsSettings/VMHostDnsSettings.md
Documentation/DSCResources/VMHostNtpSettings/VMHostNtpSettings.md
Documentation/DSCResources/VMHostSatpClaimRule/VMHostSatpClaimRule.md
Documentation/DSCResources/VMHostService/VMHostService.md
Documentation/DSCResources/VMHostSettings/VMHostSettings.md
Documentation/DSCResources/VMHostSyslog/VMHostSyslog.md
Documentation/DSCResources/VMHostTpsSettings/VMHostTpsSettings.md
Documentation/DSCResources/vCenterSettings/vCenterSettings.md
Documentation/DSCResources/vCenterStatistics/vCenterStatistics.md
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostDnsSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostNtpSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostSatpClaimRule_Config.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostService_Config.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostTpsSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerCLISettingsConfigs/PowerCLISettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/vCenterSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/vCenterStatistics_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/PowerCLISettings/PowerCLISettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostDnsSettings/VMHostDnsSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostNtpSettings/VMHostNtpSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSatpClaimRule/VMHostSatpClaimRule_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostService/VMHostService_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSettings/VMHostSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSyslog/VMHostSyslog_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostTpsSettings/VMHostTpsSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/vCenterSettings/vCenterSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/vCenterStatistics/vCenterStatistics_Config.ps1

Small fixes on formatting for all Configurations

---

Source/VMware.vSphereDSC/Classes/InventoryBaseDSC.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1

Added InventoryBaseDSC class

---

CODING_GUIDELINES.md

Added DependsOn section in CODING_GUIDELINES.md

---

CODING_GUIDELINES.md
STYLE_GUIDELINES.md

Added STYLE_GUIDELINES.md

---

Documentation/DSCResources/VMHostVss/VMHostVss.md
Documentation/DSCResources/VMHostVssSecurity/VMHostVssSecurity.md
Source/VMware.vSphereDSC/Classes/VMHostNetworkBaseDSC.ps1
Source/VMware.vSphereDSC/Classes/VMHostVssBaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/ESXiConfigs/VMHostVss/VMHostVssSecurity_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVss.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssSecurity.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostVss/VMHostVss_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostVssSecurity/VMHostVssSecurity_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostSyslog.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostVss/VMHostVssSecurity.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMwareVimTypes.cs
Source/VMware.vSphereDSC/Tests/Unit/VMHostSyslog.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostVss/VMHostVss.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostVss/VMHostVssSecurity.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

New PR after changes on master
Review comments from previous PR
Added VMHostVssSecurity
Rewrite Update-Network
Remove New-VssConfiguration
Update VMHostSyslog Integration test
Update VMHostVss Integration test
Rewrite Unit test VMHostVt commit --amend --signoffss.Unit.Tests.ps1
Signed-off-by: Luc Dekens <dekens.luc@gmail.com>

VMHostVSS - VMHostVssSecurity

---

Documentation/DSCResources/DrsCluster/DrsCluster.md
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/Cluster/DrsCluster_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Cluster/DrsCluster.ps1
Source/VMware.vSphereDSC/DSCResources/Cluster/HACluster.ps1
Source/VMware.vSphereDSC/Enums/Cluster/DrsAutomationLevel.ps1
Source/VMware.vSphereDSC/Tests/Integration/Cluster/DrsCluster.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/Cluster/HACluster.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/DrsCluster/DrsCluster_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/Cluster/DrsCluster.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Cluster/HACluster.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMwareVimTypes.cs
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

Implemented DrsCluster Resource

---

Documentation/DSCResources/Cluster/Cluster.md
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/Cluster/Cluster_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Cluster/Cluster.psd1
Source/VMware.vSphereDSC/DSCResources/Cluster/Cluster.schema.psm1

Implemented Cluster Composite Resource

---

Source/VMware.vSphereDSC/VMware.vSphereDSC.build.ps1

Added module versioning to the build pipeline

---

Documentation/DSCResources/Cluster/Cluster.md
Documentation/DSCResources/DrsCluster/DrsCluster.md
Documentation/DSCResources/HACluster/HACluster.md
Source/VMware.vSphereDSC/Classes/DatacenterInventoryBaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/Cluster/Cluster_Config.ps1
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/Cluster/DrsCluster_Config.ps1
Source/VMware.vSphereDSC/Configurations/vCenterConfigs/Cluster/HACluster_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Cluster/Cluster.schema.psm1
Source/VMware.vSphereDSC/DSCResources/Cluster/DrsCluster.ps1
Source/VMware.vSphereDSC/DSCResources/Cluster/HACluster.ps1
Source/VMware.vSphereDSC/Tests/Integration/Cluster/DrsCluster.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/Cluster/HACluster.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/DrsCluster/DrsCluster_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/HACluster/HACluster_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/Cluster/DrsCluster.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Cluster/HACluster.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/InventoryBaseDSC.Unit.Tests.ps1

Refactored InventoryBaseDSC class

---

Examples/VMHost_Config.ps1
Examples/vCenter_Config.ps1

Added Example Configurations with multiple DSC Resources

---

README.md

Fix broken link to Configuration file in README.md

---

Documentation/DSCResources/Folder/Folder.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/Folder_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Folder.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/Folder/Folder_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Folder.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Folder.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/FolderMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1

Example for Folder Resource:
```powershell
Folder MyFolder {
Server = $Server
Credential = $Credential
Name = 'MyFolder'
Location = ''
DatacenterName = 'Datacenter'
DatacenterLocation = ''
Ensure = 'Present'
FolderType = 'Host'
}
```

Add Folder Resource

---

Documentation/DSCResources/Datacenter/Datacenter.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/Datacenter_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Datacenter.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/Datacenter/Datacenter_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Datacenter.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Datacenter.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/DatacenterMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1

Example for Datacenter Resource:
```powershell
Datacenter MyDatacenter {
Server = $Server
Credential = $Credential
Name = 'MyDatacenter'
Location = ''
Ensure = 'Present'
}
```

Add Datacenter Resource

---

Documentation/DSCResources/DatacenterFolder/DatacenterFolder.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/DatacenterFolder_Config.ps1
Source/VMware.vSphereDSC/DSCResources/DatacenterFolder.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/DatacenterFolder/DatacenterFolder_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/DatacenterFolder.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/DatacenterFolder.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/DatacenterFolderMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1

Example for DatacenterFolder Resource:
```powershell
DatacenterFolder MyFolder {
Server = $Server
Credential = $Credential
Name = 'MyFolder'
Location = ''
Ensure = 'Present'
}
```

Add DatacenterFolder Resource

---

Source/VMware.vSphereDSC/Classes/DatacenterInventoryBaseDSC.ps1
Source/VMware.vSphereDSC/Classes/InventoryBaseDSC.ps1

Extend Inventory Base classes Location retrieval when Ensure is 'Absent'

---

Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVss.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssBridge.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssSecurity.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssShaping.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssTeaming.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1

Extend PopulateResult() when Ensure 'Absent' with all passed properties

---

Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostSyslog.Unit.Tests.ps1

Fix bug with Syslog values return from the Server

---

Examples/Inventory_Config.ps1
Examples/Vss_Config.ps1
Examples/vCenter_Config.ps1

Add examples with Inventory and Standard Switch (VSS) Resources

---

Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostVss/VMHostVssBridge_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostVss/VMHostVssSecurity_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostVss/VMHostVssShaping_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostVss/VMHostVssTeaming_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostVss/VMHostVss_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostVssBridge/VMHostVssBridge_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostVssTeaming/VMHostVssTeaming_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostVss/VMHostVssBridge.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostVss/VMHostVssTeaming.Integration.Tests.ps1

Introduce TestSetup for VMHostVssBridge and VMHostVssTeaming Integration Tests

---

CODING_GUIDELINES.md

Update documentation for Unit and Integration Tests

---

Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostSyslog_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostSyslog/VMHostSyslog_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/TestHelpers/IntegrationTests.Constants.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostSyslog.Integration.Tests.ps1

Introduce TestSetup for VMHostSyslog Integration Tests

---

Documentation/DSCResources/VMHostAdvancedSettings/VMHostAdvancedSettings.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostAdvancedSettings_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostAdvancedSettings.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostAdvancedSettings/VMHostAdvancedSettings_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/TestHelpers/IntegrationTests.Constants.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostAdvancedSettings.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostAdvancedSettingsMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostAdvancedSettings.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Added VMHostAdvancedSettings DSC Resource.
- Added Unit Tests for VMHostAdvancedSettings DSC Resource.
- Added Integration Tests for VMHostAdvancedSettings DSC Resource.
- Added Documentation and example Configuration for VMHostAdvancedSettings DSC Resource.

VMHostAdvancedSettings DSC Resource

---

Documentation/DSCResources/VMHostAgentVM/VMHostAgentVM.md
Source/VMware.vSphereDSC/Classes/BaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostAgentVM_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostAgentVM.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostAgentVM/VMHostAgentVM_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostAgentVM.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostAgentVMMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostAgentVM.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Added VMHostAgentVM DSC Resource.
- Added Unit Tests for VMHostAgentVM DSC Resource.
- Added Integration Tests for VMHostAgentVM DSC Resource.
- Added Documentation and example Configuration for VMHostAgentVM DSC Resource.
- Moved vCenterProductId Constant to BaseDSC class.

VMHostAgentVM DSC Resource

---

Documentation/DSCResources/VMHostPowerPolicy/VMHostPowerPolicy.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostPowerPolicy_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostPowerPolicy.ps1
Source/VMware.vSphereDSC/Enums/PowerPolicy.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostPowerPolicy/VMHostPowerPolicy_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/TestHelpers/IntegrationTests.Constants.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostPowerPolicy.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostPowerPolicyMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostPowerPolicy.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Added VMHostPowerPolicy DSC Resource.
- Added Unit Tests for VMHostPowerPolicy DSC Resource.
- Added Integration Tests for VMHostPowerPolicy DSC Resource.
- Added Documentation and example Configuration for VMHostPowerPolicy DSC Resource.

VMHostPowerPolicy DSC Resource

---

Source/VMware.vSphereDSC/Classes/VMHostBaseDSC.ps1
Source/VMware.vSphereDSC/Classes/VMHostVssBaseDSC.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostAdvancedSettings.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostCache.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVss.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssBridge.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssSecurity.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssShaping.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostVss/VMHostVssTeaming.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostService.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostSettings.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostSyslog.ps1
Source/VMware.vSphereDSC/DSCResources/vCenterSettings.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Logging.psm1
Source/VMware.vSphereDSC/VMware.vSphereDSC.build.ps1

- VMware.vSphereDSC.Logging module is introduced.
- Added Write-VerboseLog and Write-WarningLog functions to Logging module.
- Changed logging mechanism from Write-Verbose to Write-VerboseLog and Write-Warning to Write-WarningLog.

Introduce VMware.vSphereDSC.Logging module 

---

Documentation/Tips-&-Tricks.md
README.md

- Added Tips & Tricks page from Wiki to Documentation.
- Extend README.md with how to install VMware.vSphereDSC Module from PowerShell Gallery.

Tips & Tricks added to Documentation

---

Documentation/DSCResources/Cluster/Cluster.md
Documentation/DSCResources/Datacenter/Datacenter.md
Documentation/DSCResources/DatacenterFolder/DatacenterFolder.md
Documentation/DSCResources/Folder/Folder.md
Documentation/DSCResources/PowerCLISettings/PowerCLISettings.md
Documentation/DSCResources/VDSwitch/VDSwitch.md
Documentation/DSCResources/VMHostAccount/VMHostAccount.md
Documentation/DSCResources/VMHostAdvancedSettings/VMHostAdvancedSettings.md
Documentation/DSCResources/VMHostAgentVM/VMHostAgentVM.md
Documentation/DSCResources/VMHostCache/VMHostCache.md
Documentation/DSCResources/VMHostGraphics/VMHostGraphics.md
Documentation/DSCResources/VMHostGraphicsDevice/VMHostGraphicsDevice.md
Documentation/DSCResources/VMHostPciPassthrough/VMHostPciPassthrough.md
Documentation/DSCResources/VMHostPhysicalNic/VMHostPhysicalNic.md
Documentation/DSCResources/VMHostPowerPolicy/VMHostPowerPolicy.md
Documentation/DSCResources/VMHostService/VMHostService.md
Documentation/DSCResources/VMHostSettings/VMHostSettings.md
Documentation/DSCResources/VMHostSyslog/VMHostSyslog.md
Documentation/DSCResources/VMHostVssNic/VMHostVssNic.md
Documentation/DSCResources/VMHostVssPortGroup/VMHostVssPortGroup.md
Documentation/DSCResources/VMHostVssPortGroupSecurity/VMHostVssPortGroupSecurity.md
Documentation/DSCResources/VMHostVssPortGroupShaping/VMHostVssPortGroupShaping.md
Documentation/DSCResources/VMHostVssPortGroupTeaming/VMHostVssPortGroupTeaming.md
Documentation/DSCResources/vCenterSettings/vCenterSettings.md

- Fixed spacing around **Description** in all DSC Resources Documentation.

Fix Markdown formatting

---

Documentation/DSCResources/VMHostSyslog/VMHostSyslog.md

- Changed **DefaultRotateSize** to **DefaultSize** in VMHostSyslog DSC Resource Documentation.

Correction of DefaultRotateSize to DefaultSize

---

Documentation/DSCResources/VDPortGroup/VDPortGroup.md
Documentation/DSCResources/VDSwitch/VDSwitch.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDPortGroup/VDPortGroup_CreateVDPortGroupViaReferenceVDPortGroup_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDPortGroup/VDPortGroup_CreateVDPortGroup_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDPortGroup/VDPortGroup_RemoveVDPortGroup_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDSwitch_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VDPortGroup.ps1
Source/VMware.vSphereDSC/DSCResources/VDSwitch.ps1
Source/VMware.vSphereDSC/Enums/PortBinding.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VDPortGroup/VDPortGroup_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VDSwitch/VDSwitch_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VDPortGroup.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VDSwitch.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VDPortGroupMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VDSwitchMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
Source/VMware.vSphereDSC/Tests/Unit/VDPortGroup.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VDSwitch.Unit.Tests.ps1

- Added VDPortGroup DSC Resource.
- Added Unit Tests for VDPortGroup DSC Resource.
- Added Integration Tests for VDPortGroup DSC Resource.
- Added Documentation and example Configurations for VDPortGroup DSC Resource.
- Changed ReferenceVDSwitch property of VDSwitch DSC Resource to ReferenceVDSwitchName.

VDPortGroup DSC Resource

---

Documentation/DSCResources/VDSwitchVMHost/VDSwitchVMHost.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VDSwitchVMHost_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VDSwitchVMHost.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VDSwitchVMHost/VDSwitchVMHost_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VDSwitch.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VDSwitchVMHost.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VDSwitchVMHostMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VDSwitchVMHost.Unit.Tests.ps1

- Added VDSwitchVMHost DSC Resource.
- Added Unit Tests for VDSwitchVMHost DSC Resource.
- Added Integration Tests for VDSwitchVMHost DSC Resource.
- Added Documentation and example Configuration for VDSwitchVMHost DSC Resource.

VDSwitchVMHost DSC Resource

---

Documentation/DSCResources/VMHostAuthentication/VMHostAuthentication.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostAuthentication/VMHostAuthentication_JoinDomain_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostAuthentication/VMHostAuthentication_LeaveDomain_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostAuthentication.ps1
Source/VMware.vSphereDSC/Enums/DomainAction.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostAuthentication/VMHostAuthentication_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostAuthentication.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostAuthenticationMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostAuthentication.Unit.Tests.ps1

- Added VMHostAuthentication DSC Resource.
- Added Unit Tests for VMHostAuthentication DSC Resource.
- Added Integration Tests for VMHostAuthentication DSC Resource.
- Added Documentation and example Configurations for VMHostAuthentication DSC Resource.

VMHostAuthentication DSC Resource

---

Documentation/DSCResources/VMHostRole/VMHostRole.md
Source/VMware.vSphereDSC/Classes/BaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostRole/VMHostRole_CreateRoleWithPrivileges_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostRole/VMHostRole_RemoveRole_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostAccount.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostRole.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostRole/VMHostRole_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostRole.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostRoleMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostRole.Unit.Tests.ps1

- Added VMHostRole DSC Resource.
- Added Unit Tests for VMHostRole DSC Resource.
- Added Integration Tests for VMHostRole DSC Resource.
- Added Documentation and example Configurations for VMHostRole DSC Resource.
- Moved EnsureConnectionIsESXi method from VMHostAccount DSC Resource to BaseDSC class and added WriteDscResourceState method to BaseDSC class.

VMHostRole DSC Resource

---

Documentation/DSCResources/NfsDatastore/NfsDatastore.md
Documentation/DSCResources/VmfsDatastore/VmfsDatastore.md
Source/VMware.vSphereDSC/Classes/DatastoreBaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsDatastore/NfsDatastore_CreateNfsDatastoreWithReadOnlyAccessMode_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsDatastore/NfsDatastore_CreateNfsDatastoreWithReadWriteAccessMode_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsDatastore/NfsDatastore_RemoveNfsDatastore_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VmfsDatastore/VmfsDatastore_CreateVmfsDatastore_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VmfsDatastore/VmfsDatastore_RemoveVmfsDatastore_Config.ps1
Source/VMware.vSphereDSC/DSCResources/Datastore/NfsDatastore.ps1
Source/VMware.vSphereDSC/DSCResources/Datastore/VmfsDatastore.ps1
Source/VMware.vSphereDSC/Enums/Datastore/AccessMode.ps1
Source/VMware.vSphereDSC/Enums/Datastore/AuthenticationMethod.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/NfsDatastore/NfsDatastore_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VmfsDatastore/VmfsDatastore_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Datastore/NfsDatastore.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/Datastore/VmfsDatastore.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Datastore/DatastoreBaseDSC.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Datastore/NfsDatastore.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/Datastore/VmfsDatastore.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/DatastoreBaseDSCMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/NfsDatastoreMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VmfsDatastoreMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1

- Introduced DatastoreBaseDSC class.
- Added VmfsDatastore and NfsDatastore DSC Resources.
- Added Unit Tests for DatastoreBaseDSC class, VmfsDatastore and NfsDatastore DSC Resources.
- Added Integration Tests for VmfsDatastore and NfsDatastore DSC Resources.
- Added Documentation and example Configurations for VmfsDatastore and NfsDatastore DSC Resources.

VmfsDatastore and NfsDatastore DSC Resources

---

Documentation/DSCResources/NfsUser/NfsUser.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsUser/NfsUser_ChangeNfsUserPassword_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsUser/NfsUser_CreateNfsUser_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/NfsUser/NfsUser_RemoveNfsUser_Config.ps1
Source/VMware.vSphereDSC/DSCResources/NfsUser.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/NfsUser/NfsUser_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/NfsUser.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/NfsUser.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/NfsUserMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1

- Added NfsUser DSC Resource.
- Added Unit Tests for NfsUser DSC Resource.
- Added Integration Tests for NfsUser DSC Resource.
- Added Documentation and example Configurations for NfsUser DSC Resource.

NfsUser DSC Resource

---

Documentation/DSCResources/vCenterVMHost/vCenterVMHost.md
Source/VMware.vSphereDSC/Classes/BaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/vCenterVMHost/vCenterVMHost_AddVMHostTovCenterAndImportResourcePoolHierarchy_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/vCenterVMHost/vCenterVMHost_AddVMHostTovCenter_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/vCenterVMHost/vCenterVMHost_RemoveVMHostFromvCenter_Config.ps1
Source/VMware.vSphereDSC/DSCResources/vCenterVMHost.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/vCenterVMHost/vCenterVMHost_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/vCenterVMHost/vCenterVMHost.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/vCenterVMHost/vCenterVMHost.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/vCenterVMHostMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/vCenterVMHost.Unit.Tests.ps1

- Added vCenterVMHost DSC Resource.
- Added Unit Tests for vCenterVMHost DSC Resource.
- Added Integration Tests for vCenterVMHost DSC Resource.
- Added Documentation and example Configurations for vCenterVMHost DSC Resource.

vCenterVMHost DSC Resource

---

Documentation/DSCResources/VMHostConfiguration/VMHostConfiguration.md
Source/VMware.vSphereDSC/Classes/BaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostConfiguration/VMHostConfiguration_ModifyVMHostCryptoKey_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostConfiguration/VMHostConfiguration_ModifyVMHostHostProfileAssociation_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostConfiguration/VMHostConfiguration_ModifyVMHostLicenseKeyTimeZoneVMSwapfileDatastoreAndPolicy_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostConfiguration/VMHostConfiguration_ModifyVMHostState_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostConfiguration.ps1
Source/VMware.vSphereDSC/Enums/VMHostState.ps1
Source/VMware.vSphereDSC/Enums/VMSwapfilePolicy.ps1
Source/VMware.vSphereDSC/Enums/VsanDataMigrationMode.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostConfiguration/VMHostConfiguration_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostConfiguration/VMHostConfiguration.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostConfiguration/VMHostConfiguration.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostConfigurationMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
Source/VMware.vSphereDSC/Tests/Unit/VMHostConfiguration.Unit.Tests.ps1

- Added VMHostConfiguration DSC Resource.
- Added Unit Tests for VMHostConfiguration DSC Resource.
- Added Integration Tests for VMHostConfiguration DSC Resource.
- Added Documentation and example Configurations for VMHostConfiguration DSC Resource.

VMHostConfiguration DSC Resource

---

Source/VMware.vSphereDSC/Classes/EsxCliBaseDSC.ps1
Source/VMware.vSphereDSC/Tests/Unit/EsxCli/EsxCliBaseDSC.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/EsxCliBaseDSCMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Introduced EsxCliBaseDSC class.
- Added Unit Tests for EsxCliBaseDSC class.

EsxCliBaseDSC class

---

Documentation/DSCResources/VMHostDCUIKeyboard/VMHostDCUIKeyboard.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/EsxCli/VMHostDCUIKeyboard/VMHostDCUIKeyboard_ModifyVMHostDCUIKeyboardLayout_Config.ps1
Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostDCUIKeyboard.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostDCUIKeyboard/VMHostDCUIKeyboard_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostDCUIKeyboard/VMHostDCUIKeyboard.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostDCUIKeyboard/VMHostDCUIKeyboard.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/EsxCli/VMHostDCUIKeyboard.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostDCUIKeyboardMocks.ps1

- Added VMHostDCUIKeyboard DSC Resource.
- Added Unit Tests for VMHostDCUIKeyboard DSC Resource.
- Added Integration Tests for VMHostDCUIKeyboard DSC Resource.
- Added Documentation and example Configuration for VMHostDCUIKeyboard DSC Resource.

VMHostDCUIKeyboard DSC Resource

---

Documentation/DSCResources/VMHostIPRoute/VMHostIPRoute.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostNetwork/VMHostIPRoute/VMHostIPRoute_CreateVMHostIPRoute_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostNetwork/VMHostIPRoute/VMHostIPRoute_RemoveVMHostIPRoute_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostNetwork/VMHostIPRoute/VMHostIPRoute.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostIPRoute/VMHostIPRoute_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostNetwork/VMHostIPRoute/VMHostIPRoute.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostNetwork/VMHostIPRoute/VMHostIPRoute.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIPRouteMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostNetwork/VMHostIPRoute/VMHostIPRoute.Unit.Tests.ps1

- Added VMHostIPRoute DSC Resource.
- Added Unit Tests for VMHostIPRoute DSC Resource.
- Added Integration Tests for VMHostIPRoute DSC Resource.
- Added Documentation and example Configurations for VMHostIPRoute DSC Resource.

VMHostIPRoute DSC Resource

---

Documentation/DSCResources/VMHostNetworkCoreDump/VMHostNetworkCoreDump.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/EsxCli/VMHostNetworkCoreDump/VMHostNetworkCoreDump_ModifyVMHostNetworkCoreDumpConfiguration_Config.ps1
Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostNetworkCoreDump.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostNetworkCoreDump/VMHostNetworkCoreDump_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostNetworkCoreDump/VMHostNetworkCoreDump.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostNetworkCoreDump/VMHostNetworkCoreDump.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/EsxCli/VMHostNetworkCoreDump.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostNetworkCoreDumpMocks.ps1

- Added VMHostNetworkCoreDump DSC Resource.
- Added Unit Tests for VMHostNetworkCoreDump DSC Resource.
- Added Integration Tests for VMHostNetworkCoreDump DSC Resource.
- Added Documentation and example Configuration for VMHostNetworkCoreDump DSC Resource.

VMHostNetworkCoreDump DSC Resource

---

Documentation/DSCResources/VMHostAcceptanceLevel/VMHostAcceptanceLevel.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/EsxCli/VMHostAcceptanceLevel/VMHostAcceptanceLevel_ModifyVMHostAcceptanceLevel_Config.ps1
Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostAcceptanceLevel.ps1
Source/VMware.vSphereDSC/Enums/AcceptanceLevel.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostAcceptanceLevel/VMHostAcceptanceLevel_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostAcceptanceLevel/VMHostAcceptanceLevel.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostAcceptanceLevel/VMHostAcceptanceLevel.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/EsxCli/VMHostAcceptanceLevel.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostAcceptanceLevelMocks.ps1

- Added VMHostAcceptanceLevel DSC Resource.
- Added Unit Tests for VMHostAcceptanceLevel DSC Resource.
- Added Integration Tests for VMHostAcceptanceLevel DSC Resource.
- Added Documentation and example Configuration for VMHostAcceptanceLevel DSC Resource.

VMHostAcceptanceLevel DSC Resource

---

Documentation/DSCResources/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/EsxCli/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration_AddVMHostvSANNetworkConfigurationIPInterface_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/EsxCli/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration_RemoveVMHostvSANNetworkConfigurationIPInterface_Config.ps1
Source/VMware.vSphereDSC/DSCResources/EsxCli/VMHostvSANNetworkConfiguration.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/EsxCli/VMHostvSANNetworkConfiguration/VMHostvSANNetworkConfiguration.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/EsxCli/VMHostvSANNetworkConfiguration.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostvSANNetworkConfigurationMocks.ps1

- Added VMHostvSANNetworkConfiguration DSC Resource.
- Added Unit Tests for VMHostvSANNetworkConfiguration DSC Resource.
- Added Integration Tests for VMHostvSANNetworkConfiguration DSC Resource.
- Added Documentation and example Configurations for VMHostvSANNetworkConfiguration DSC Resource.

VMHostvSANNetworkConfiguration DSC Resource

---

Documentation/DSCResources/VMHostScsiLunPath/VMHostScsiLunPath.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostScsiLunPath/VMHostScsiLunPath_ConfigureScsiLunPathToBeActiveAndPreferred_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostScsiLunPath.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostScsiLunPath/VMHostScsiLunPath_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostScsiLunPath/VMHostScsiLunPath.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostScsiLunPath/VMHostScsiLunPath.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostScsiLunPathMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostScsiLunPath.Unit.Tests.ps1

- Added VMHostScsiLunPath DSC Resource.
- Added Unit Tests for VMHostScsiLunPath DSC Resource.
- Added Integration Tests for VMHostScsiLunPath DSC Resource.
- Added Documentation and example Configuration for VMHostScsiLunPath DSC Resource.

VMHostScsiLunPath DSC Resource

---

Documentation/DSCResources/VMHostScsiLun/VMHostScsiLun.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostScsiLun/VMHostScsiLun_ModifyVMHostScsiLunConfigurationWithFixedMultipathPolicy_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostScsiLun/VMHostScsiLun_ModifyVMHostScsiLunConfigurationWithRoundRobinMultipathPolicy_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostScsiLun/VMHostScsiLun_RemoveScsiDiskPartitions_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostScsiLun.ps1
Source/VMware.vSphereDSC/Enums/MultipathPolicy.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostScsiLun/VMHostScsiLun_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostScsiLun/VMHostScsiLun.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostScsiLun/VMHostScsiLun.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostScsiLunMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostScsiLun.Unit.Tests.ps1

- Added VMHostScsiLun DSC Resource.
- Added Unit Tests for VMHostScsiLun DSC Resource.
- Added Integration Tests for VMHostScsiLun DSC Resource.
- Added Documentation and example Configurations for VMHostScsiLun DSC Resource.

VMHostScsiLun DSC Resource

---

Documentation/DSCResources/VMHostFirewallRuleset/VMHostFirewallRuleset.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostFirewallRuleset/VMHostFirewallRuleset_EnableVMHostFirewallRulesetAndModifyTheAllowedIPAddressesList_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostFirewallRuleset.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostFirewallRuleset/VMHostFirewallRuleset_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostFirewallRuleset/VMHostFirewallRuleset.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostFirewallRuleset/VMHostFirewallRuleset.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostFirewallRulesetMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/VMHostFirewallRuleset.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Added VMHostFirewallRuleset DSC Resource.
- Added Unit Tests for VMHostFirewallRuleset DSC Resource.
- Added Integration Tests for VMHostFirewallRuleset DSC Resource.
- Added Documentation and example Configuration for VMHostFirewallRuleset DSC Resource.

VMHostFirewallRuleset DSC Resource

---

Documentation/DSCResources/VMHostIScsiHba/VMHostIScsiHba.md
Documentation/DSCResources/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget.md
Source/VMware.vSphereDSC/Classes/VMHostIScsiHbaBaseDSC.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHba/VMHostIScsiHba_ConfigureCHAPSettingsOfIScsiHostBusAdapterWithProhibitedChapType_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHba/VMHostIScsiHba_ConfigureCHAPSettingsOfIScsiHostBusAdapterWithRequiredChapType_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget_CreateIScsiHostBusAdapterSendTargetWithRequiredChapType_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget_CreateIScsiHostBusAdapterStaticTargetWithInheritedChapSettings_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget_RemoveIScsiHostBusAdapterSendTarget_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHba.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHbaTarget.ps1
Source/VMware.vSphereDSC/Enums/ChapType.ps1
Source/VMware.vSphereDSC/Enums/IScsiHbaTargetType.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostIScsiHba/VMHostIScsiHba_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaTarget/VMHostIScsiHbaTarget.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIScsiHbaBaseDSCMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIScsiHbaMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIScsiHbaTargetMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHba/VMHostIScsiHba.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHba/VMHostIScsiHbaBaseDSC.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHba/VMHostIScsiHbaTarget.Unit.Tests.ps1

- Introduced VMHostIScsiHbaBaseDSC class.
- Added VMHostIScsiHba DSC Resource.
- Added VMHostIScsiHbaTarget DSC Resource.
- Added Unit Tests for VMHostIScsiHbaBaseDSC class.
- Added Unit Tests for VMHostIScsiHba DSC Resource.
- Added Unit Tests for VMHostIScsiHbaTarget DSC Resource.
- Added Integration Tests for VMHostIScsiHba DSC Resource.
- Added Integration Tests for VMHostIScsiHbaTarget DSC Resource.
- Added Documentation and example Configurations for VMHostIScsiHba DSC Resource.
- Added Documentation and example Configurations for VMHostIScsiHbaTarget DSC Resource.

VMHostIScsiHba and VMHostIScsiHbaTarget DSC Resources

---

Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVss.ps1
Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssBridge.ps1
Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssSecurity.ps1
Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssShaping.ps1
Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssTeaming.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Fixed bugs with nullable properties for all Standard Switch DSC Resources.

Bugfixes for nullable properties for all Standard Switch DSC Resources

---

Build/build.ps1
README.md
Source/VMware.vSphereDSC/DSCResources/VMHostTpsSettings.ps1
Source/VMware.vSphereDSC/RequiredModules.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1

- Added **VMware.VimAutomation.Vds** as dependency in module manifest.
- Updated README.md section for available DSC Resources.
- Fixed bug with Tps setting not exposed in VMHostTpsSettings DSC Resource.

Module manifest dependencies

---

Build/build.ps1
Source/VMware.vSphereDSC/RequiredModules.ps1

- Added VMware.VimAutomation.Storage as dependency of VMware.vSphereDSC.

VMware.VimAutomation.Storage as dependency of VMware.vSphereDSC

---

Examples/VMHost_Authentication_Config.ps1
Examples/VMHost_IScsiHba_Config.ps1
Examples/VMHost_NetworkMigrationToDistributedSwitch_Config.ps1
Examples/VMHost_Network_Config.ps1
Examples/VMHost_Storage_Config.ps1

- Added example DSC Configurations for VMHost Authentication, Storage and Network.

Example DSC Configurations

---

Source/VMware.vSphereDSC/ExportVMHostConfiguration.ps1

- Fixed bugs with multiple dependencies for StandardSwitch, VMHostDnsSettings and VMHostPermission DSC Resources in ExportVMHostConfiguration script.

Bugfix for multiple dependencies in ExportVMHostConfiguration script

---

Source/VMware.vSphereDSC/ExportVMHostConfiguration.ps1

- Added support for specifying which VMHost DSC Resources to export in ExportVMHostConfiguration script.

Support for specifying which VMHost DSC Resources to export

---

Documentation/DSCResources/DatastoreCluster/DatastoreCluster.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/DatastoreCluster/DatastoreCluster_CreateDatastoreCluster_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/DatastoreCluster/DatastoreCluster_RemoveDatastoreCluster_Config.ps1
Source/VMware.vSphereDSC/DSCResources/DatastoreCluster.ps1
Source/VMware.vSphereDSC/Tests/Integration/DatastoreCluster/DatastoreCluster.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/DatastoreCluster/DatastoreCluster_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/DatastoreCluster/DatastoreCluster.Mocks.Data.ps1
Source/VMware.vSphereDSC/Tests/Unit/DatastoreCluster/DatastoreCluster.Mocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/DatastoreCluster/DatastoreCluster.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/TestUtils.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs

- Added **DatastoreCluster** DSC Resource.
- Added Unit Tests for **DatastoreCluster** DSC Resource.
- Added Integration Tests for **DatastoreCluster** DSC Resource.
- Added Documentation and example Configurations for **DatastoreCluster** DSC Resource.
- Extended **TestUtils** with helper function for importing the **VMware.vSphereDSC** module.

DatastoreCluster DSC Resource

---

Documentation/DSCResources/DRSRule/DRSRule.md
Source/VMware.vSphereDSC/Classes/InventoryUtil.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/DRSRule/DRSRule_CreateDRSRule_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/DRSRule/DRSRule_RemoveDRSRule_Config.ps1
Source/VMware.vSphereDSC/DSCResources/DRSRule.ps1
Source/VMware.vSphereDSC/Enums/DRSRuleType.ps1
Source/VMware.vSphereDSC/Tests/Integration/DRSRule/DRSRule.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/DRSRule/DRSRule.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/DRSRule/DRSRule_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/DRSRule/DRSRule.Mocks.Data.ps1
Source/VMware.vSphereDSC/Tests/Unit/DRSRule/DRSRule.Mocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/DRSRule/DRSRule.Unit.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs

- Introduced **InventoryUtil** class.
- Added **DRSRule** DSC Resource.
- Added Unit Tests for **DRSRule** DSC Resource.
- Added Integration Tests for **DRSRule** DSC Resource.
- Added Documentation and example Configurations for **DRSRule** DSC Resource.

DRSRule DSC Resource

---

Source/VMware.vSphereDSC/DSCResources/Cluster/Cluster.schema.psm1
Source/VMware.vSphereDSC/DSCResources/StandardPortGroup/StandardPortGroup.schema.psm1
Source/VMware.vSphereDSC/DSCResources/StandardSwitch/StandardSwitch.schema.psm1
Source/VMware.vSphereDSC/VMware.vSphereDSC.CompositeResourcesHelper.ps1

- Changed the implementation of the **New-DscResourceBlock()** in **VMware.vSphereDSC.CompositeResourcesHelper.ps1** to return the created **DscResourceBlock** instead of invoking it inside the function.

Added fix for New-DscResourceBlock in CompositeResourcesHelper.ps1

---

Source/VMware.vSphereDSC/RequiredModules.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.psd1

- Moved comment section, explaining the dependencies of the **VMware.vSphereDSC** module from **RequiredModules.ps1** to **VMware.vSphereDSC.psd1**.

Fixed issue of comments getting duplicated after build process

---

Source/VMware.vSphereDSC/DSCResources/VMHostAccount.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostAccount.Unit.Tests.ps1

- Fixed the bug with determiting the desired state, when the **ESXi** account password should be changed.

Fix bug with desired state when Account password should be changed

---

.travis.yml
Build/VMware.PSDSCUnitTestsRunner.ps1
Build/build.ps1
Build/common.ps1
Build/enableExperimentalFeature.ps1

- Added **BuildFlags** enumeration that tracks the steps which need to be performed during the build process.
- The build now detects what changes have been made in order to run the tests and build functions only when a module code is changed.

Build modifications to run the tests only when a module code is changed

---

Documentation/vSphereNodes.md
LIMITATIONS.md
Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
Source/VMware.PSDesiredStateConfiguration/Functions/Errors.ps1
Source/VMware.PSDesiredStateConfiguration/Functions/Invoke-VmwDscConfiguration.ps1
Source/VMware.PSDesiredStateConfiguration/Functions/KeyPropertyResourceCheckDotNet.ps1
Source/VMware.PSDesiredStateConfiguration/Tests/Unit/Invoke-VmwDscConfiguration.tests.ps1

- Extend ***-VmwDscConfiguration** cmdlets vaildation to check for **DSC Resources** with duplicate key properties.

Extend *-VmwDscConfiguration cmdlets vaildation for duplicate key properties

---

Source/VMware.vSphereDSC/DSCResources/StandardSwitch/VMHostVssTeaming.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Fixed bugs with physical network adapters when updating the teaming policy of the standard switch.

Fix bugs with physical network adapters when updating the teaming policy of the standard switch

---

Documentation/DSCResources/VMHostIScsiHba/VMHostIScsiHba.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHba/VMHostIScsiHba_ModifyIScsiNameOfIScsiHostBusAdapter_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHba.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VMHostIScsiHba/VMHostIScsiHba_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHba/VMHostIScsiHba.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VMHostIScsiHbaMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHba/VMHostIScsiHba.Unit.Tests.ps1

- Added **IScsiName** property of **VMHostIScsiHba DSC Resource**.
- Added Unit Tests for **IScsiName** property of **VMHostIScsiHba DSC Resource**.
- Added Integration Tests for **IScsiName** property of **VMHostIScsiHba DSC Resource**.
- Added Documentation and example Configuration for **IScsiName** property of **VMHostIScsiHba DSC Resource**.

[Feature] IScsiName property of VMHostIScsiHba DSC Resource

---

Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Configurations/vSphereNodeConfiguration.ps1
Source/VMware.PSDesiredStateConfiguration/Tests/Integration/Invoke-VmwDscConfiguration.Integration.Tests.ps1
Source/VMware.PSDesiredStateConfiguration/Tests/Integration/ServerConfig.ps1

- Added integration tests for **VMware.PSDesiredStateConfiguration** module.

Integration Tests for VMware.PSDesiredStateConfiguration

---

Documentation/DSCResources/VDPortGroup/VDPortGroup.md
Source/VMware.vSphereDSC/Configurations/PowerShell/vCenterConfigs/VDPortGroup/VDPortGroup_CreateVDPortGroup_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VDPortGroup.ps1
Source/VMware.vSphereDSC/Tests/Integration/Configurations/VDPortGroup/VDPortGroup_Config.ps1
Source/VMware.vSphereDSC/Tests/Integration/VDPortGroup.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/MockData.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/Mocks/VDPortGroupMocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/PowerCLITypes.cs
Source/VMware.vSphereDSC/Tests/Unit/TestHelpers/VMware.VimAutomation.Core/VMware.VimAutomation.Core.psm1
Source/VMware.vSphereDSC/Tests/Unit/VDPortGroup.Unit.Tests.ps1

- Added **VLanId** property of **VDPortGroup DSC Resource**.
- Added Unit Tests for **VLanId** property of **VDPortGroup DSC Resource**.
- Added Integration Tests for **VLanId** property of **VDPortGroup DSC Resource**.
- Added Documentation and example Configuration for **VLanId** property of **VDPortGroup DSC Resource**.

[Feature] VLanId property of VDPortGroup DSC Resource

---

Documentation/DSCResources/VMHostStorage/VMHostStorage.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostStorage/VMHostStorage_EnableSoftwareIscsi_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostStorage.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostStorage/VMHostStorage_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Mocks.Data.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Mocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostStorage/VMHostStorage.Unit.Tests.ps1

- Added **VMHostStorage** DSC Resource.
- Added Unit Tests for **VMHostStorage** DSC Resource.
- Added Integration Tests for **VMHostStorage** DSC Resource.
- Added Documentation and example Configurations for **VMHostStorage** DSC Resource.

VMHostStorage DSC Resource

---

Documentation/DSCResources/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.md
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_BindVMKernelNicsToIscsiHba_Config.ps1
Source/VMware.vSphereDSC/Configurations/PowerShell/ESXiConfigs/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_UnbindVMKernelNicsToIscsiHba_Config.ps1
Source/VMware.vSphereDSC/DSCResources/VMHostIScsiHbaVMKernelNic.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Integration.Tests.Helpers.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Integration.Tests.ps1
Source/VMware.vSphereDSC/Tests/Integration/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic_Config.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Mocks.Data.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Mocks.ps1
Source/VMware.vSphereDSC/Tests/Unit/VMHostIScsiHbaVMKernelNic/VMHostIScsiHbaVMKernelNic.Unit.Tests.ps1
Source/VMware.vSphereDSC/VMware.vSphereDSC.Helper.psm1

- Added **VMHostIScsiHbaVMKernelNic** DSC Resource.
- Added Unit Tests for **VMHostIScsiHbaVMKernelNic** DSC Resource.
- Added Integration Tests for **VMHostIScsiHbaVMKernelNic** DSC Resource.
- Added Documentation and example Configurations for **VMHostIScsiHbaVMKernelNic** DSC Resource.

VMHostIScsiHbaVMKernelNic DSC Resource

---

README.md

- Added **Getting Started** sections for **VMware.vSphereDSC** and **VMware.PSDesiredStateConfiguration** modules in **README.md**.

Add Getting Started sections for VMware.vSphereDSC and VMware.PSDesiredStateConfiguration

---

Source/VMware.PSDesiredStateConfiguration/Classes/DscConfigurationFileParser.ps1
Source/VMware.PSDesiredStateConfiguration/Classes/DscItems.ps1
Source/VMware.PSDesiredStateConfiguration/Functions/New-VmwDscConfiguration.ps1
Source/VMware.PSDesiredStateConfiguration/Tests/Unit/New-VmwDscConfiguration.tests.ps1
Source/VMware.PSDesiredStateConfiguration/VMware.PSDesiredStateConfiguration.psd1

- Added a new **Path** parameter for the **New-VmwDscConfiguration** cmdlet which specifies a file path to file containing **DSC Configurations**.
- Added a new **ConfigurationName** parameter for the **New-VmwDscConfiguration** cmdlet which specifies the **DSC Configuration** to compile from the specified **DSC Configurations** file.
- Renamed the **CustomParams** parameter of the **New-VmwDscConfiguration** cmdlet to **Parameters** which works with script parameters instead of configuration parameters only.
- Removed the **ConfigName** parameter from the  **New-VmwDscConfiguration** cmdlet.
- Removed the **ConfigurationData** parameter from the  **New-VmwDscConfiguration** cmdlet.

[Feature] Implement parsing PowerShell script file containing DSC Configurations in New-VmwDscConfiguration cmdlet

---

Documentation/vSphereNodes.md
VMware.PSDesiredStateConfiguration.md

- Modified the documentation of the **VMware.PSDesiredStateConfiguration** module to reflect the changes made in the **New-VmwDscConfiguration** cmdlet.

[Improvement] VMware.PSDesiredStateConfiguration module documentation

---

Documentation/DSCResources/VMHostVssNic/VMHostVssNic.md
VMware.PSDesiredStateConfiguration.md
VMware.vSphereDSC.md

- Added installation guide for **VMware.PSDesiredStateConfiguration** module.
- Updated the **VMHostVssNic DSC Resource** documentation to be the same as the one in the [Wiki](https://github.com/vmware/dscr-for-vmware/wiki).

[Impovement] Add installation guide for VMware.PSDesiredStateConfiguration module
